{
 "title": "Supermicro Server IPMI Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "servers",
    "label": "All IPMI",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"server\""
    }
   },
   {
    "name": "rams",
    "label": "RAMS",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ipmi_sensor\" WITH KEY = \"name\"\nWHERE \"name\" =~ /.*dimm.*_temp$/ AND \"server\" =~ /^$servers$/"
    }
   },
   {
    "name": "SSD",
    "label": "ssd",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ipmi_sensor\"\nWITH KEY = \"status_desc\"\nWHERE \"name\" = 'hdd_status'\nORDER BY time DESC\nLIMIT 10"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Temperatures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 1",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /CPU[0-9]+ Temp/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "cpu1_temp" }
     ]
    },
    {
     "alias": "CPU 2",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /CPU[0-9]+ Temp/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "cpu2_temp" }
     ]
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PSU 1",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /Vcpu[0-9]|12V|5VCC|3.3VCC|5VSB|3.3VSB/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "ps1_status" },
      { "condition": "AND", "key": "server::tag", "operator": "=~", "value": "/^$servers$/" }
     ]
    },
    {
     "alias": "PSU 2",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /Vcpu[0-9]|12V|5VCC|3.3VCC|5VSB|3.3VSB/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "ps2_status" }
     ]
    }
   ]
  },
  {
   "title": "System Temperature ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "orderBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "query": "SELECT last(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /PS[0-9]+ Status|Chassis Intru/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "system_temp" }
     ]
    }
   ]
  },
  {
   "title": "Supermicro SSD Status - All Servers",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "Fan Speeds",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FAN 1",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /^FAN[0-9]+$/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "fan1" }
     ]
    },
    {
     "alias": "FAN 2",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /^FAN[0-9]+$/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "fan2" }
     ]
    },
    {
     "alias": "FAN 3",
     "bucket": "telegraf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE \"name\" =~ /^FAN[0-9]+$/ AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "fan3" }
     ]
    }
   ]
  },
  {
   "title": "RAM Temperature  ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=~", "value": "/^$servers$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$rams$/" }
     ]
    }
   ]
  }
 ]
}